global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "trafficflow_rules.yml"

scrape_configs:
  - job_name: 'trafficflow-ai'
    static_configs:
      - targets: ['trafficflow-ai:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']
    scrape_interval: 30s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093
